trigger:
- main

pool:
  name: Default   # ðŸ‘ˆ EXACT agent pool name

steps:
- checkout: self

- bash: |
    node -v
    npm -v
    npm install
    node index.js
  displayName: "Run Node.js app"





